# permissions for end users to view frontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: frontend-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-example
    app.kubernetes.io/part-of: operator-example
    app.kubernetes.io/managed-by: kustomize
  name: frontend-viewer-role
rules:
- apiGroups:
  - web.tsdb.top
  resources:
  - frontends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.tsdb.top
  resources:
  - frontends/status
  verbs:
  - get
